### ISSUE TITLE
Question with how to do this on SPA apps

### ISSUE THREAD

**Issue by denjaland** [reshadman/laravel-optimistic-locking#2]
Hi,

I was reading through the docs, and I see that for business transactions, you say that you can keep track of the lock version on the page.
But in your controller, I guess, you need to do the following?

    class SomeController {
        public function update(Request $request, SomeModel $model) {

            // since $model is retrieved from the database, it will have the most recent lock...
            // am I right in thinking that we need to manually set the lock version here always?
            $model->lock_version = $request->get('lock_version');

            // This will then throw an exception when the lock version of the database differs from what I got from the $request
            $model->save();
        }
    }

Is this correct, or is there a more intelligent way to pass this on?

**Comment by reshadman** [comment]
Yes it is true.  The client should always have and send the lock version, and the controller or any client request processor should always specify the version it is mutating just in any possible way like the one you mentioned. Or you can define new decorator methods like `saveWithVersion($version...);` or override the original `save` method and send the `version` through the `$options` variable which the save method signature accepts in eloquent.
